FROM ubuntu:18.04

LABEL description="This file generates a docker image containing everything needed to build and run wagtail application"

RUN apt-get update && apt-get install -y python3 python3-setuptools

WORKDIR /data

CMD [ tail -f /dev/null ]
